#!/bin/bash

# Script Name:                  Ops 301 - Challenge 06
# Author:                       Amleset Tesfamariam
# Date of latest revision:      09/04/2023
# Purpose:                      To create a script in Python using bash commands.
# Reason:                       It is useful to be able to code in multiple languages using different commands.


# Declaration of variables














# End