#!/bin/bash

# Script Name:                  Ops 301 - Challenge 07
# Author:                       Amleset Tesfamariam
# Date of latest revision:      09/05/2023
# Purpose:                      To create a script in Python that displays all directories and files within.
# Reason:                       Finding and listing directories/files can be helpful for troubleshooting.


# Declaration of variables














# End