#!/bin/bash

# Script Name:                  Ops 301 - Challenge 10
# Author:                       Amleset Tesfamariam
# Date of latest revision:      09/08/2023
# Purpose:                      To create a Python script that creates a new file, appends, writes, and deletes using file handling commands.
# Reason:                       It is important to know how to use file handling commands to readily control and access file contents.


# Declaration of variables














# End