#!/bin/bash

# Script Name:                  Ops 301 - Challenge 08
# Author:                       Amleset Tesfamariam
# Date of latest revision:      09/06/2023
# Purpose:                      To create a script in Python that qualify certain conditions including: assigning a variable list to multiple string elements, printing elements from this list, and changing the values within this list.
# Reason:                       It is important to know how to create, edit, find, and add to lists of different variables.


# Declaration of variables














# End